### ISSUE TITLE
Extension does not appear if the username contains a hyphen.

### ISSUE THREAD

**Issue by alessandro-gentilini** [mbostock/bl.ocks.org#1]
Hello, I installed this extension in Google Chrome but I have some problem.

If I go to https://gist.github.com/mbostock/963c4d246e96963856bf I can see the button "bl.ocks" at the right of the "Download ZIP" button but if I go to https://gist.github.com/alessandro-gentilini/c07039f3d5dea29f767c the button "bl.ocks" is not there.

What am I missing? Do I need to be "registered" on http://bl.ocks.org/ in order to use it?

Thank you.
Alessandro Gentilini

**Comment by mbostock** [comment]
The issue is that you have a hyphen in your username, and there’s a bug where the extension doesn’t detect Gists when the username has a hyphen. Changing the title of this issue accordingly.

**Comment by mbostock** [comment]
More precisely, the username regular expression is `/^[a-z0-9][a-z0-9]*$/i`; it should be more lenient.

**Comment by alessandro-gentilini** [comment]
Thank you!
