### ISSUE TITLE
Replace Showdown with Marked.js

### ISSUE THREAD

**Issue by mbostock** [mbostock/bl.ocks.org#11]
We’re running an ancient version of Showdown.

**Comment by Arkadiy292** [comment]
ok, Супер..

**Comment by Arkadiy292** [comment]
не получается.. может позже?

**Comment by mbloch** [comment]
Or,  try switching to the current version of Showdown, which appears to support GFM like this:  `showdown.setFlavor('github');`

**Comment by mbostock** [comment]
Updated to the latest Showdown (1.8.1). Thanks for recommendation.
