### ISSUE TITLE
Chrome extension disabled -- not listed in Chrome web store?

### ISSUE THREAD

**Issue by SpaceActuary** [mbostock/bl.ocks.org#45]
I installed the Chrome bl.ocks.org extension after downloading it from the bl.ocks.org [home page](http://bl.ocks.org).

It worked after reloading the tab, but after relaunching Chrome, the extension was disabled and I was taken to the following page: https://support.google.com/chrome/answer/2811969?p=ui_remove_non_cws_extensions&rd=1

Can this extension be added to the Chrome Web Store, or Is there a version in the Chrome Web Store that I should install instead?

I'm using Chrome Version 39.0.2171.95 m.

**Comment by saurfang** [comment]
I, too, would appreciate if this can be submitted to the Chrome Web Store. However, for me, the workaround is to unpack the crx file to a folder, go to extension manager in Chrome, check developer mode, then load unpacked extension.

**Comment by mbostock** [comment]
It’s now available [on the Chrome Web Store](https://chrome.google.com/webstore/detail/blocksorg/phjkbonaifennbfpmieeipknnkhaoiaf).
