### ISSUE TITLE
Main viewer shows reference to a broken link for which there is no gist anymore.

### ISSUE THREAD

**Issue by EE2dev** [mbostock/bl.ocks.org#47]
On my bl.ocks viewer page there is a reference to a gist which does not exist anymore. How do I delete it ?

http://bl.ocks.org/EE2dev

The link to item explorer (http://bl.ocks.org/EE2dev/d1c86cc47ad2759d955e) is a dead link. I have no entry about it on gist any more. How do I delete the reference to the broken link?  

Thanks!

**Comment by mbostock** [comment]
It was cached. It appears to have been fixed now.

**Comment by EE2dev** [comment]
Thanks, Mike!
Yes, it is fixed now.
