### ISSUE TITLE
[bl.ocks.org, the website] license in `.block` not recognized?

### ISSUE THREAD

**Issue by ghost** [mbostock/bl.ocks.org#5]
neither [mit](https://bl.ocks.org/b6618480f41089451fb445abf20f521e/a13c7c6afa3978edad908ae796822b16846db327) nor [apache-2.0](https://bl.ocks.org/b6618480f41089451fb445abf20f521e/cd6e33ef9b08a05cdedbac15d737fe25c7c4f4cc)

not being accepted as valid "license strings" for some reason, so block is being "not licenced"

(i havent found the repo/issues for actual `bl.ocks.org`)

**Comment by mbostock** [comment]
The problem is not the license but the lack of a `.block` file. You have a `_.block` file, where _ is a space character.

**Comment by ghost** [comment]
that kind of error would take me a long time to find.. thanks!
