### ISSUE TITLE
Actual block height is 78px not 80px

### ISSUE THREAD

**Issue by techtonik** [mbostock/bl.ocks.org#50]
Is it a bug that thumbnail height should be 78px to prevent wobbling? Or should people just make thumbnails 78px tall?

**Comment by techtonik** [comment]
![blocks78](https://cloud.githubusercontent.com/assets/515889/8761380/a6ea3f82-2d57-11e5-9b76-1a3ba80f97b4.png)

**Comment by mbostock** [comment]
Thanks. This has been fixed.

**Comment by techtonik** [comment]
Yes. Great. The only thing is that I fail to see a commit that does that.

**Comment by mbostock** [comment]
The website is no longer open-source, so you won’t see the commit history. But it has been fixed.

**Comment by techtonik** [comment]
Why no open source? Somebody made a mirror, put ads and stole the traffic?
