### ISSUE TITLE
Delay after Gist update

### ISSUE THREAD

**Issue by jamesleesaunders** [mbostock/bl.ocks.org#52]
I am not sure if this is just something we simply have to live with (due to caches CDN etc), but there is often a considerable delay after editing a Gist and its changed then being reflected on their associated bl.ock.

Is there any way this can be made instant?

I often tweak a gist but have to wait a while in between saves to see the results.

**Comment by mbostock** [comment]
The gists are cached up to five minutes. Currently bl.ocks.org runs on a single free Heroku instance, so I must make heavy use of in-memory caching to avoid hitting API and resource limits. Unless you are proposing to fund additional resources for this project, caching is the only way it can work.

**Comment by jamesleesaunders** [comment]
Thanks Mike! I would love to support but I am not sure I have enough cash for you!

You do a great service to humanity with D3 (and bl.ocks) :-) 

All the best,
Jim
