### ISSUE TITLE
Chrome and FF extension not visible

### ISSUE THREAD

**Issue by cool-Blue** [mbostock/bl.ocks.org#53]
I installed the chrome extension (it's a great idea, if my assumption about what it does is correct) but there is no icon showing.  I verified that it is enabled and I'm not in incognito mode so I assume there should be an icon to click which will automatically redirect from the gist to bl.ocks.org?  
I also tried in FF but same result.  I'm using Windows 7.  

I checked the source code and `document.querySelector(".gist-sidebar")`  returns null...  
PR submitted to align with the structure I see in Gist.

**Comment by jamesleesaunders** [comment]
I think a recent gist site change broke it. The link I on disappeared a couple of weeks ago when GitHub changed.

**Comment by cool-Blue** [comment]
Yes, it's easy enough to fix (once you figure out how). I submitted a PR including commits for two options: one with the hex logo added to the button and one without.  I did it for chrome and firefox only because I'm not confident testing safari. Hopefully it's ok.

**Comment by alignedleft** [comment]
Just confirming that, yes, the extension isn't displaying the "view block" button in either Safari (foreground) or Chrome (background):

![screen shot 2015-09-04 at 9 33 00 am](https://cloud.githubusercontent.com/assets/1034002/9689042/14de84ca-52e8-11e5-946e-60ba87dfc5a9.png)

**Comment by mbostock** [comment]
Fixed in 1.3.5, which is waiting approval from the respective stores.

**Comment by alignedleft** [comment]
Thanks, @mbostock!
