### ISSUE TITLE
Hide Secret gists from gallery view?

### ISSUE THREAD

**Issue by syntagmatic** [mbostock/bl.ocks.org#56]
I was experimenting with removing bl.ocks from the gallery. Deleting works after the cache has cleared, but it doesn't look like making gists "secret" (turning off the public flag) removes them from the gallery. For instance this one has been secret for a few days now:

http://bl.ocks.org/syntagmatic/3719418
<img width="324" alt="screen shot 2015-08-18 at 3 09 48 pm" src="https://cloud.githubusercontent.com/assets/156229/9344119/3377ea50-45bb-11e5-8223-142ed5ce2280.png">

Is there any way to hide gists from the gallery view without deleting them?

**Comment by mbostock** [comment]
Hmm. I don’t see it in your list: http://bl.ocks.org/syntagmatic

Are you sure it wasn’t your browser that was caching it?

**Comment by syntagmatic** [comment]
That was it, thanks!
