### ISSUE TITLE
Error in loading gist (Index.html is not parsed correctly)

### ISSUE THREAD

**Issue by oikonang** [mbostock/bl.ocks.org#6]
There is something really strange going on and I think that it is Gist's fault. Check at this example: https://bl.ocks.org/oikonang/2ddc174270177a4111c90627277775ed

**Comment by mbostock** [comment]
You’ll have to be more specific about what the perceived problem is. The syntax highlighting of your index.html file seems not great, but that appears to be a problem with [highlight.js](https://highlightjs.org/) misidentifying your HTML as XML. But I’m probably not going to do anything to fix that, sorry.
