### ISSUE TITLE
Hide gists that are not blocks from gallery

### ISSUE THREAD

**Issue by ahmohamed** [mbostock/bl.ocks.org#62]
[My gallery](http://bl.ocks.org/ahmohamed) is showing gists that do not contain the main files for a block (README.md, index.html). Is there a way to hide them from the gallery? Shouldn't these gist be filtered out by default?

**Comment by ahmohamed** [comment]
For some reason, the issue is already fixed.

**Comment by mbostock** [comment]
Sorry, I fixed this recently and forgot to close this issue. Thanks for the report.
