### ISSUE TITLE
use github-flavoured-markdown?

### ISSUE THREAD

**Issue by ghost** [mbostock/bl.ocks.org#7]
[source code](https://gist.githubusercontent.com/noformnocontent/44ec7f42064db81bc41cd502f030c681/raw/c45cb4074968d212c30adf0e6cdb4467d68dd0ef/readme.md)
![source code](https://cloud.githubusercontent.com/assets/23745012/24830508/f747193e-1c87-11e7-8b24-f581011f31e5.png)

[how it should be](https://gist.github.com/noformnocontent/44ec7f42064db81bc41cd502f030c681/c45cb4074968d212c30adf0e6cdb4467d68dd0ef)
![how it should be](https://cloud.githubusercontent.com/assets/23745012/24830507/f74341a6-1c87-11e7-8ab8-f5e591ef748d.png)

[how it is now on blocks](https://bl.ocks.org/noformnocontent/44ec7f42064db81bc41cd502f030c681/c45cb4074968d212c30adf0e6cdb4467d68dd0ef)
![how it is now on blocks](https://cloud.githubusercontent.com/assets/23745012/24830509/f7473aea-1c87-11e7-8061-c9f768b69dfe.png)

**Comment by mbostock** [comment]
I’m currently using [Showdown](https://github.com/showdownjs/showdown) to render Markdown. I also tried [Marked](https://github.com/chjj/marked), but it produces the same output, even though it claims to support GitHub-flavored Markdown:

https://bl.ocks.org/mbostock/raw/2e12b742af65a48ae16e67015cf6f408/

If you can point me to a pure-JavaScript Markdown renderer that is more consistent with GitHub, please let me know, and I will look into switching to it.
