### ISSUE TITLE
suggested copyedit to guide users toward successfully including a license

### ISSUE THREAD

**Issue by jgravois** [mbostock/bl.ocks.org#9]
hello! in https://bl.ocks.org/-/about you write:

> Customize the appearance of your Block by adding a .block YAML configuration. The following options are supported:

> * license - a supported SPDX license code

i might be dense, but i took this to mean:
```yaml
.block.yaml
license - apache-2.0
```
after some trial and error and comparing with an existing block with a license i obviously figured out that the file extension was superfluous and that i should be using a colon as a separator, but a small change to the copy would make it a no brainer.

my suggestion:

> Customize the appearance of your Block by adding a .block file which incorporates the YAML below:

> *license - a supported SPDX license code
> ...

> example: 
>```yaml
>license: gpl-3.0
>height: 600
>scrolling: yes
>border: no

if the source for the page above is on GitHub somewhere that alluded me i'd be happy to open a PR for this small change.

thanks for all you do!

**Comment by mbostock** [comment]
Good idea. Added. Thank you!
